"""empty message

Revision ID: 1ad92bd63dac
Revises: 
Create Date: 2026-03-23 16:22:41.203732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad92bd63dac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('room_code', sa.String(), nullable=True),
    sa.Column('qr_code_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_code')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_email'), ['email'], unique=True)

    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('sign_in_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sign_out_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'EXPIRED', name='status_enum'), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('alert_30_sent', sa.Boolean(), nullable=False),
    sa.Column('alert_10_sent', sa.Boolean(), nullable=True),
    sa.CheckConstraint('duration IS NULL OR duration >= 0', name='ck_attendance_duration_non_negative'),
    sa.CheckConstraint('sign_out_time IS NULL OR sign_out_time > sign_in_time', name='ck_attendance_signout_after_signin'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index('ix_attendance_room_signin', ['room_id', 'sign_in_time'], unique=False)
        batch_op.create_index('ix_attendance_sign_in_time', ['sign_in_time'], unique=False)
        batch_op.create_index('ix_attendance_student_status', ['student_id', 'status'], unique=False)
        batch_op.create_index('uq_attendance_one_active_per_student', ['student_id'], unique=True, sqlite_where=sa.text("status = 'ACTIVE'"), postgresql_where=sa.text("status = 'ACTIVE'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index('uq_attendance_one_active_per_student', sqlite_where=sa.text("status = 'ACTIVE'"), postgresql_where=sa.text("status = 'ACTIVE'"))
        batch_op.drop_index('ix_attendance_student_status')
        batch_op.drop_index('ix_attendance_sign_in_time')
        batch_op.drop_index('ix_attendance_room_signin')

    op.drop_table('attendance_records')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_email'))

    op.drop_table('students')
    op.drop_table('rooms')
    # ### end Alembic commands ###
