"""empty message

Revision ID: 7f5f918e0418
Revises: 2b3d4e5f6a7b
Create Date: 2026-04-09 01:47:45.475451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f5f918e0418'
down_revision = '2b3d4e5f6a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # The original enum was created without PENDING, but the application
    # now uses it for pending-room-session enforcement.
    op.execute("ALTER TYPE status_enum ADD VALUE IF NOT EXISTS 'PENDING'")

    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_authorized_at', sa.DateTime(), nullable=True))
        batch_op.create_index('uq_attendance_one_pending_per_student', ['student_id'], unique=True, sqlite_where=sa.text("status = 'PENDING'"), postgresql_where=sa.text("status = 'PENDING'"))

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('room_code',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('room_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index('uq_attendance_one_pending_per_student', sqlite_where=sa.text("status = 'PENDING'"), postgresql_where=sa.text("status = 'PENDING'"))
        batch_op.drop_column('admin_authorized_at')

    # ### end Alembic commands ###
